### ISSUE TITLE
How to use with laravel-mix (webpack)

### ISSUE THREAD

**Issue by muuvmuuv** [kenwheeler/cash#292] opened 2019-06-12 07:03 UTC
I'm running into trouble getting cash working in my laravel/vue application. I'm using [laravel-mix](https://github.com/JeffreyWay/laravel-mix/) to bundle my files to production. Mix provides a function called `autoload` which is inside webpacks default `ProvidePlugin`.

But when I go to my website it says `[Vue warn]: Error in mounted hook: "TypeError: $ is not a function"` but when I have a look at my compile file I see that it is requiring it:

```
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! cash-dom */ "./node_modules/cash-dom/dist/cash.esm.js")))
```

Any hint on that? Does a pure webpack example exists?

I also created an issue at laravel-mix with more informations: https://github.com/JeffreyWay/laravel-mix/issues/2127

**Comment by limonte** [comment] 2019-06-12 08:29
I guess the issue is somehow related to the fact that webpack will prefer `cash.esm.js` (ES module) over `cash.js` by default, see #268 for some hints

**Comment by limonte** [comment] 2019-06-12 08:32
Try adding `"browser": "./dist/cash.js",` to `node_modules/cash-dom/package.json` (as it's done in #291) and let us know if that helped

**Comment by muuvmuuv** [comment] 2019-06-12 08:41
@limonte fixed it. Really strange that webpack does not default to main...

**Comment by limonte** [comment] 2019-06-12 08:44
> Really strange that webpack does not default to main...

Here's their reasoning: https://github.com/webpack/webpack/issues/5756

@fabiospampinato I think #291 should be merged as it already helped for at least in 3 different cases.

**Comment by fabiospampinato** [comment] 2019-06-19 13:48
@limonte I haven't had the time to check that it works under all supported environments (https://github.com/kenwheeler/cash/issues/268#issuecomment-498821678), I'll get this done around the end of the month probably.

**Comment by limonte** [comment] 2019-07-04 13:06
@fabiospampinato ping, just making sure this issue isn't lost from your todo list :)

**Comment by fabiospampinato** [comment] 2019-07-04 13:07
It didn't get lost, I'm working on getting [Notable](https://github.com/notable/notable) v1.6 ready right now, there's been a bit of a delay.

**Comment by fabiospampinato** [comment] 2019-07-12 16:10
Finally got some time for this and a few issues that needs to be addressed, I'm working on them right now 👍

**Comment by fabiospampinato** [comment] 2019-07-12 17:12
Closing this in favor of https://github.com/kenwheeler/cash/issues/268

**Closed by fabiospampinato** 2019-07-12 17:12 UTC
