### ISSUE TITLE
Consider enabling scheduled builds in Travis

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#224] opened 2018-10-20 06:18 UTC
### Feature description

https://docs.travis-ci.com/user/cron-jobs/

### Feature motivation

> If software isn't tested, it doesn't work (c)

In the unstable JS ecosystem, the statement above can be rephrased to: 

> If software isn't tested on a daily basis, it doesn't work 

The daily (scheduled) build can be enabled in Travis settings: https://travis-ci.org/kenwheeler/cash/settings

**Comment by limonte** [comment] 2018-10-20 06:19
After setting up daily builds, you'll be notified about any failure by Travis and/or one of tools made for monitoring, e.g. CatLight, here's my dashboard:

![image](https://user-images.githubusercontent.com/6059356/47252214-48918e80-d449-11e8-87d6-5f4f760cbf9c.png)

**Comment by fabiospampinato** [comment] 2018-10-20 11:46
What's the point of this? Assuming that a build passed already once, or that if it didn't pass because of SauceLabs I'll restart it manually before publishing a release anyway, this doesn't seem very useful 🤔

**Comment by limonte** [comment] 2018-10-21 06:46
1. There's no `lock` file in the repo, which means there's no guarantee the same versions of dev deps will be used
2. JS ecosystem gives too little fucks about semver, which means breaking changes could happen in minor and patch releases
1 + 2 results in 3. I the build is passing today, there's no guarantee it will pass tomorrow

Which will result in potentially bad DX (developer experience):
1. A contributor sends a PR
2. build fails
3. A contributor opens the Travis build log and realize it's not his fault

---

In CI, **C** stands for **continuous**. Continuous testing means catching issues before users will catch them which will lead to their happiness. But, their happiness might not be your priority and that's fine :)

**Comment by fabiospampinato** [comment] 2018-10-21 11:47
I've enabled daily builds because after all it's just a setting on a page, and unless it causes too much noise due to SauceLabs not working properly at times it doesn't do any harm.

But I think you're somewhat exaggerating here:

> There's no lock file in the repo, which means there's no guarantee the same versions of dev deps will be used

Even if there was a `yarn.lock` file there's no guarantee that somebody will run `yarn install` rather than `npm install`, and vice versa. Even if they did that they could encounter bugs that have been fixed in subsequent patch releases.

> JS ecosystem gives too little fucks about semver

I guess that changes on a package-to-package basis, it's not like nobody cares about semver in the JS ecosystem.

> which means breaking changes could happen in minor and patch releases

People make mistakes, even somebody who follows semver perfectly can introduce a regression in a patch release, which you might not actually catch if you're using a lock file.

> Which will result in potentially bad DX (developer experience):
> - A contributor sends a PR
> - Build fails
> - A contributor opens the Travis build log and realize it's not his fault

This could still happen.

> In CI, C stands for continuous. Continuous testing means catching issues before users will catch them which will lead to their happiness. But, their happiness might not be your priority and that's fine :)

That's actually a weird definition of "continuous", be definition doing something once a day, unless that thing takes a day to complete, is a discrete thing, not a continuous one.

We have no dependencies so I'm sure our users don't care about this at all.

By no means CI assures you that all issues will be caught before the users, or at all.

**Closed by fabiospampinato** 2018-10-21 11:47 UTC
Labels: needs more info

**Comment by limonte** [comment] 2018-10-22 03:12
> We have no dependencies so I'm sure our users don't care about this at all.

All you said is correct except this statement. Every JS package has quite a lot of dependencies - **browsers** the're working with :) The next version of Chrome or Firefox could break something and you will be notified about that automatically. 

BTW, should we add Firefox latest to Travis build along with Chrome latest?

**Comment by fabiospampinato** [comment] 2018-10-22 11:19
That's a good point, is there a special syntax for testing on the latest version of a browser? We are currently testing always on the same versions so I don't think daily builds help there.
