### ISSUE TITLE
Append on select causes error in insertContent

### ISSUE THREAD

**Issue by acburst** [kenwheeler/cash#169] opened 2017-09-22 00:53 UTC
When you try to append a select field with options to anything it errors. The options are moved individually before it errors.

**Comment by millerlogic** [comment] 2018-01-09 01:31
I just got bitten by this issue. A select element acts like an array of its options, so it has a length. insertContent checks if the child length is truthy to iterate its elements, but it should not be doing this.

It also means if you try to append an empty cash object $(), the length check will not be truthy (0 length) so it will try to append the cash object itself and will fail.

**Comment by fabiospampinato** [comment] 2018-05-11 19:46
@acburst I've just tried the following and it worked for me (I'm on v2.1.2):

```js
$(document.body).append('<select name="foo"><option value="1">One</option><option value="2">Two</option></select>');
```

Can you check again if the issue is still occurring in v2.1.2, and if so, can you provide more detailed steps on how to reproduce the issue?

**Comment by fabiospampinato** [comment] 2018-07-04 23:01
No needed info provided, I'm closing this.

**Closed by fabiospampinato** 2018-07-04 23:01 UTC
Labels: needs more info
