### ISSUE TITLE
Release notes and CHANGELOG are missing for 3.0.0-beta.0 and 3.0.0-beta.1

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#231] opened 2018-10-28 12:02 UTC
Recently two beta bumps of a new major release were made. As per semver, a major version contains **incompatible** API changes.

How users are supposed to test out the new betas without a description of breaking changes? There should be either GitHub release with a release notes or CHANGELOG.md

---

My recommendation is: stop doing releases manually, there are robots to help us with repetivive processes. `semantic-release` is perfect, integration into `cash` will take approx 2 hours for you including reading docs and understanding basics of automated releasing.

@fabiospampinato If you don't have time/will to implement `semantic-release` by yourself, I can help with that. Let me know if you have any questions/doubts about `semantic-release`.

**Comment by fabiospampinato** [comment] 2018-10-28 13:31
Yeah I forgot about that, thanks for pointing this out.

`semantic-release` sounds interesting but from what I can understand about it by skimming the readme it doesn't sound like a good fit for me personally and maybe for `cash` too:

- By design it picks a version number for you, which is something I don't like. I wonder how a tool like this is supposed to decide if the next version should be `3.0.0`, `3.0.0-alpha.0` or `3.0.0-beta.0` for instance.

- In order to do that it looks like it needs commits messages written in a particular way, I don't want to write commits messages like that.

- It writes a changelog for you, which is nice, but these things sometimes need a human touch before releasing them. For instance there's no point in including many changes about internals in changelogs. A tool like this wouldn't understand the difference.

Automating changelogs and releases is something I'm interested in though. A while ago I actually made an [extension](https://github.com/fabiospampinato/vscode-bump) for vscode for automating changelog updates, it could do automatic releases too. Also btw we need to bump the version numbers we are hardcoding in the readme, it doesn't look like `semantic-release` can do that, but I might be wrong.

For now you'll have to read the commits history to learn about the breaking changes, in the near-ish future I'm going to:

- [ ] Add support for generating the changelog file, including writing the changes for previous versions, to `vscode-bump`.
- [ ] Add support for automatically making a GitHub release, which includes the latest changes, to `vscode-bump`.
- [ ] Use `vscode-bump` for releases.

Maybe also:

- [ ] Extract the core functionalities out of the extension into `bump-cli` or something, a tool link this shouldn't be so tied with the editor it's running in.

**Comment by fabiospampinato** [comment] 2019-01-15 02:55
I've made a proper tool out of `vscode-bump`: [bump](https://github.com/fabiospampinato/bump).

I'm closing this as now everything is configured for automatic version updates, changelog updates, GitHub releases and NPM releases. Bump also created a [changelog](https://github.com/kenwheeler/cash/blob/master/CHANGELOG.md) for the repo, it goes back to the very first version, I think it's quite nice.

**Closed by fabiospampinato** 2019-01-15 02:55 UTC
Labels: enhancement

**Comment by limonte** [comment] 2019-01-15 06:09
Good news! Added my star to it but without an intention to even try it unless it has any tests. Some people are saying "if it's not tested, it's broken".

What would be main advantages of `bump` comparing with https://github.com/webpro/release-it (which has a proper code coverage btw)?

**Comment by fabiospampinato** [comment] 2019-01-15 14:40
@limonte I think tests catch only a subset of all the possible bugs, in my experience they mostly catch regression bugs. Unfortunately I have to decide between adding comprehensive tests to everything I do and do more, some times I choose the latter.

> What would be main advantages of bump comparing with https://github.com/webpro/release-it

Let's discuss about this in the issue you opened.
