### ISSUE TITLE
Please consider adding $.ajax 

### ISSUE THREAD

**Issue by drnkwati** [kenwheeler/cash#161] opened 2017-05-08 07:07 UTC
Cool library. It will be nice to have a jquery like Ajax method with compatible Syntax. Response type json text, XML etc. Please can we have that functionality included?

**Comment by hultberg** [comment] 2017-05-08 07:42
This has been discussed several other times, see #103

**Comment by fabiospampinato** [comment] 2018-05-11 20:01
Closing as duplicate of https://github.com/kenwheeler/cash/issues/103.

**Closed by fabiospampinato** 2018-05-11 20:01 UTC
